[package]
name = "mini-search-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
[package]
name = "axum-web"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
