server:
  name: "Mini Search Engine"

crawler:
  domains_file: "domains"
  log_interval_per_domain: 500
  max_pages_per_domain: 10000

indexer:
  # Clear any existing index and do the initial crawl again.
  new_index: true
  commit_interval_ms: 2000
  db_name: "data/stats.db"
  search_index_dir: "data/search_index"
  results_per_query: 10
  tech_term_boost: 1.5
