server:
  name: "Mini Search Engine"
  results_per_query: 10

crawler:
  domains_file: "domains"
  log_interval_per_domain: 500
  max_pages_per_domain: 10000

indexer:
  # Clear any existing index and do the initial crawl again.
  new_index: false
  index_dir: "data/search_index"
  db_file: "data/stats.db"
  commit_interval_ms: 2000
  tech_term_boost: 1.5
